export const FETCH_FEED_LIST_REQUEST = "FETCH_FEED_LIST_REQUEST";
export const FETCH_FEED_LIST_SUCCESS = "FETCH_FEED_LIST_SUCCESS";
export const FETCH_FEED_LIST_FAILURE = "FETCH_FEED_LIST_FAILURE";
// naviagtion
export const FETCH_CATEGORIES_REQUEST = "FETCH_CATEGORIES_REQUEST";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE";
// store cid
export const STORE_CID_SUCCESS = "STORE_CID_SUCCESS";
// news
export const FETCH_NEWS_REQUEST = "FETCH_NEWS_REQUEST";
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const FETCH_NEWS_FAILURE = "FETCH_NEWS_FAILURE";
// news details
export const FETCH_NEWS_DETAILS_REQUEST = "FETCH_NEWS_DETAILS_REQUEST";
export const FETCH_NEWS_DETAILS_SUCCESS = "FETCH_NEWS_DETAILS_SUCCESS";
export const FETCH_NEWS_DETAILS_FAILURE = "FETCH_NEWS_DETAILS_FAILURE";
export const STORE_COMMON_TAB_INDEX_SUCCESS = "STORE_COMMON_TAB_INDEX_SUCCESS";
export const STORE_COMMON_DATA_SUCCESS = "STORE_COMMON_DATA_SUCCESS";
